package org.jabberstory.cjac.consignsettle.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * Organ generated by hbm2java
 */
public class Organ {

	private String organId;
	private String organName;
	private String role;
	private String businessName;
	private String projectName;
	private String researchAgency;
	private String researchResponsiblePerson;
	private String contractStartDate;
	private String contractEndDate;
	private String govContributeAmount;
	private String nonGovContributeAmount;
	private String goodsAmount;
	private String totalCashAmount;
	private String govInterests;
	private String consignSettlementCommission;
	private String useResultDate;
	private String formalObjectAcceptanceDate;
	private String formalObjectResultDate;
	private String consignSettlementResultDate;
	private String subjectResponsiblePerson;
	private String subjectResponsiblePhone1;
	private String subjectResponsiblePhone2;
	private String subjectResponsiblePhone3;
	private String subjectResponsiblePostNumber1;
	private String subjectResponsiblePostNumber2;
	private String subjectResponsibleAddress;
	private String subejctResponsibleEmail;
	private String consignSettlementPerson;
	private String consignSettlementPhone1;
	private String consignSettlementPhone2;
	private String consignSettlementPhone3;
	private String consignSettlementPostNumber1;
	private String consignSettlementPostNumber2;
	private String consignSettlementAddress;
	private String consignSettlementEmail;
	private String currentAccount;
	private String currentInterest;
	private String currentNonPropriety;
	private String currentRedemtion;
	private String currentSubTotal;
	private String costDetail;
	private String nonApproval1;
	private String nonApproval2;
	private Organ parentOrgan;
	private Set<UserGroup> userGroups = new HashSet<UserGroup>(0);

	public Organ() {
	}

	public Organ(String organName, String role, String businessName,
			String projectName, String researchAgency,
			String researchResponsiblePerson, String contractStartDate,
			String contractEndDate, String govContributeAmount,
			String nonGovContributeAmount, String goodsAmount,
			String totalCashAmount, String govInterests,
			String consignSettlementCommission, String useResultDate,
			String formalObjectAcceptanceDate, String formalObjectResultDate,
			String consignSettlementResultDate,
			String subjectResponsiblePerson, String subjectResponsiblePhone1,
			String subjectResponsiblePhone2, String subjectResponsiblePhone3,
			String subjectResponsiblePostNumber1,
			String subjectResponsiblePostNumber2,
			String subjectResponsibleAddress, String subejctResponsibleEmail,
			String consignSettlementPerson, String consignSettlementPhone1,
			String consignSettlementPhone2, String consignSettlementPhone3,
			String consignSettlementPostNumber1,
			String consignSettlementPostNumber2,
			String consignSettlementAddress, String consignSettlementEmail,
			String currentAccount, String currentInterest,
			String currentNonPropriety, String currentRedemtion,
			String currentSubTotal, String costDetail, String nonApproval1,
			String nonApproval2, Organ parentOrgan, Set<UserGroup> userGroups) {
		this.organName = organName;
		this.role = role;
		this.businessName = businessName;
		this.projectName = projectName;
		this.researchAgency = researchAgency;
		this.researchResponsiblePerson = researchResponsiblePerson;
		this.contractStartDate = contractStartDate;
		this.contractEndDate = contractEndDate;
		this.govContributeAmount = govContributeAmount;
		this.nonGovContributeAmount = nonGovContributeAmount;
		this.goodsAmount = goodsAmount;
		this.totalCashAmount = totalCashAmount;
		this.govInterests = govInterests;
		this.consignSettlementCommission = consignSettlementCommission;
		this.useResultDate = useResultDate;
		this.formalObjectAcceptanceDate = formalObjectAcceptanceDate;
		this.formalObjectResultDate = formalObjectResultDate;
		this.consignSettlementResultDate = consignSettlementResultDate;
		this.subjectResponsiblePerson = subjectResponsiblePerson;
		this.subjectResponsiblePhone1 = subjectResponsiblePhone1;
		this.subjectResponsiblePhone2 = subjectResponsiblePhone2;
		this.subjectResponsiblePhone3 = subjectResponsiblePhone3;
		this.subjectResponsiblePostNumber1 = subjectResponsiblePostNumber1;
		this.subjectResponsiblePostNumber2 = subjectResponsiblePostNumber2;
		this.subjectResponsibleAddress = subjectResponsibleAddress;
		this.subejctResponsibleEmail = subejctResponsibleEmail;
		this.consignSettlementPerson = consignSettlementPerson;
		this.consignSettlementPhone1 = consignSettlementPhone1;
		this.consignSettlementPhone2 = consignSettlementPhone2;
		this.consignSettlementPhone3 = consignSettlementPhone3;
		this.consignSettlementPostNumber1 = consignSettlementPostNumber1;
		this.consignSettlementPostNumber2 = consignSettlementPostNumber2;
		this.consignSettlementAddress = consignSettlementAddress;
		this.consignSettlementEmail = consignSettlementEmail;
		this.currentAccount = currentAccount;
		this.currentInterest = currentInterest;
		this.currentNonPropriety = currentNonPropriety;
		this.currentRedemtion = currentRedemtion;
		this.currentSubTotal = currentSubTotal;
		this.costDetail = costDetail;
		this.nonApproval1 = nonApproval1;
		this.nonApproval2 = nonApproval2;
		this.parentOrgan = parentOrgan;
		this.userGroups = userGroups;
	}

	public String getOrganId() {
		return this.organId;
	}

	public void setOrganId(String organId) {
		this.organId = organId;
	}

	public String getOrganName() {
		return this.organName;
	}

	public void setOrganName(String organName) {
		this.organName = organName;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getResearchAgency() {
		return this.researchAgency;
	}

	public void setResearchAgency(String researchAgency) {
		this.researchAgency = researchAgency;
	}

	public String getResearchResponsiblePerson() {
		return this.researchResponsiblePerson;
	}

	public void setResearchResponsiblePerson(String researchResponsiblePerson) {
		this.researchResponsiblePerson = researchResponsiblePerson;
	}

	public String getContractStartDate() {
		return this.contractStartDate;
	}

	public void setContractStartDate(String contractStartDate) {
		this.contractStartDate = contractStartDate;
	}

	public String getContractEndDate() {
		return this.contractEndDate;
	}

	public void setContractEndDate(String contractEndDate) {
		this.contractEndDate = contractEndDate;
	}

	public String getGovContributeAmount() {
		return this.govContributeAmount;
	}

	public void setGovContributeAmount(String govContributeAmount) {
		this.govContributeAmount = govContributeAmount;
	}

	public String getNonGovContributeAmount() {
		return this.nonGovContributeAmount;
	}

	public void setNonGovContributeAmount(String nonGovContributeAmount) {
		this.nonGovContributeAmount = nonGovContributeAmount;
	}

	public String getGoodsAmount() {
		return this.goodsAmount;
	}

	public void setGoodsAmount(String goodsAmount) {
		this.goodsAmount = goodsAmount;
	}

	public String getTotalCashAmount() {
		return this.totalCashAmount;
	}

	public void setTotalCashAmount(String totalCashAmount) {
		this.totalCashAmount = totalCashAmount;
	}

	public String getGovInterests() {
		return this.govInterests;
	}

	public void setGovInterests(String govInterests) {
		this.govInterests = govInterests;
	}

	public String getConsignSettlementCommission() {
		return this.consignSettlementCommission;
	}

	public void setConsignSettlementCommission(
			String consignSettlementCommission) {
		this.consignSettlementCommission = consignSettlementCommission;
	}

	public String getUseResultDate() {
		return this.useResultDate;
	}

	public void setUseResultDate(String useResultDate) {
		this.useResultDate = useResultDate;
	}

	public String getFormalObjectAcceptanceDate() {
		return this.formalObjectAcceptanceDate;
	}

	public void setFormalObjectAcceptanceDate(String formalObjectAcceptanceDate) {
		this.formalObjectAcceptanceDate = formalObjectAcceptanceDate;
	}

	public String getFormalObjectResultDate() {
		return this.formalObjectResultDate;
	}

	public void setFormalObjectResultDate(String formalObjectResultDate) {
		this.formalObjectResultDate = formalObjectResultDate;
	}

	public String getConsignSettlementResultDate() {
		return this.consignSettlementResultDate;
	}

	public void setConsignSettlementResultDate(
			String consignSettlementResultDate) {
		this.consignSettlementResultDate = consignSettlementResultDate;
	}

	public String getSubjectResponsiblePerson() {
		return this.subjectResponsiblePerson;
	}

	public void setSubjectResponsiblePerson(String subjectResponsiblePerson) {
		this.subjectResponsiblePerson = subjectResponsiblePerson;
	}

	public String getSubjectResponsiblePhone1() {
		return this.subjectResponsiblePhone1;
	}

	public void setSubjectResponsiblePhone1(String subjectResponsiblePhone1) {
		this.subjectResponsiblePhone1 = subjectResponsiblePhone1;
	}

	public String getSubjectResponsiblePhone2() {
		return this.subjectResponsiblePhone2;
	}

	public void setSubjectResponsiblePhone2(String subjectResponsiblePhone2) {
		this.subjectResponsiblePhone2 = subjectResponsiblePhone2;
	}

	public String getSubjectResponsiblePhone3() {
		return this.subjectResponsiblePhone3;
	}

	public void setSubjectResponsiblePhone3(String subjectResponsiblePhone3) {
		this.subjectResponsiblePhone3 = subjectResponsiblePhone3;
	}

	public String getSubjectResponsiblePostNumber1() {
		return this.subjectResponsiblePostNumber1;
	}

	public void setSubjectResponsiblePostNumber1(
			String subjectResponsiblePostNumber1) {
		this.subjectResponsiblePostNumber1 = subjectResponsiblePostNumber1;
	}

	public String getSubjectResponsiblePostNumber2() {
		return this.subjectResponsiblePostNumber2;
	}

	public void setSubjectResponsiblePostNumber2(
			String subjectResponsiblePostNumber2) {
		this.subjectResponsiblePostNumber2 = subjectResponsiblePostNumber2;
	}

	public String getSubjectResponsibleAddress() {
		return this.subjectResponsibleAddress;
	}

	public void setSubjectResponsibleAddress(String subjectResponsibleAddress) {
		this.subjectResponsibleAddress = subjectResponsibleAddress;
	}

	public String getSubejctResponsibleEmail() {
		return this.subejctResponsibleEmail;
	}

	public void setSubejctResponsibleEmail(String subejctResponsibleEmail) {
		this.subejctResponsibleEmail = subejctResponsibleEmail;
	}

	public String getConsignSettlementPerson() {
		return this.consignSettlementPerson;
	}

	public void setConsignSettlementPerson(String consignSettlementPerson) {
		this.consignSettlementPerson = consignSettlementPerson;
	}

	public String getConsignSettlementPhone1() {
		return this.consignSettlementPhone1;
	}

	public void setConsignSettlementPhone1(String consignSettlementPhone1) {
		this.consignSettlementPhone1 = consignSettlementPhone1;
	}

	public String getConsignSettlementPhone2() {
		return this.consignSettlementPhone2;
	}

	public void setConsignSettlementPhone2(String consignSettlementPhone2) {
		this.consignSettlementPhone2 = consignSettlementPhone2;
	}

	public String getConsignSettlementPhone3() {
		return this.consignSettlementPhone3;
	}

	public void setConsignSettlementPhone3(String consignSettlementPhone3) {
		this.consignSettlementPhone3 = consignSettlementPhone3;
	}

	public String getConsignSettlementPostNumber1() {
		return this.consignSettlementPostNumber1;
	}

	public void setConsignSettlementPostNumber1(
			String consignSettlementPostNumber1) {
		this.consignSettlementPostNumber1 = consignSettlementPostNumber1;
	}

	public String getConsignSettlementPostNumber2() {
		return this.consignSettlementPostNumber2;
	}

	public void setConsignSettlementPostNumber2(
			String consignSettlementPostNumber2) {
		this.consignSettlementPostNumber2 = consignSettlementPostNumber2;
	}

	public String getConsignSettlementAddress() {
		return this.consignSettlementAddress;
	}

	public void setConsignSettlementAddress(String consignSettlementAddress) {
		this.consignSettlementAddress = consignSettlementAddress;
	}

	public String getConsignSettlementEmail() {
		return this.consignSettlementEmail;
	}

	public void setConsignSettlementEmail(String consignSettlementEmail) {
		this.consignSettlementEmail = consignSettlementEmail;
	}

	public String getCurrentAccount() {
		return this.currentAccount;
	}

	public void setCurrentAccount(String currentAccount) {
		this.currentAccount = currentAccount;
	}

	public String getCurrentInterest() {
		return this.currentInterest;
	}

	public void setCurrentInterest(String currentInterest) {
		this.currentInterest = currentInterest;
	}

	public String getCurrentNonPropriety() {
		return this.currentNonPropriety;
	}

	public void setCurrentNonPropriety(String currentNonPropriety) {
		this.currentNonPropriety = currentNonPropriety;
	}

	public String getCurrentRedemtion() {
		return this.currentRedemtion;
	}

	public void setCurrentRedemtion(String currentRedemtion) {
		this.currentRedemtion = currentRedemtion;
	}

	public String getCurrentSubTotal() {
		return this.currentSubTotal;
	}

	public void setCurrentSubTotal(String currentSubTotal) {
		this.currentSubTotal = currentSubTotal;
	}

	public String getCostDetail() {
		return this.costDetail;
	}

	public void setCostDetail(String costDetail) {
		this.costDetail = costDetail;
	}

	public String getNonApproval1() {
		return this.nonApproval1;
	}

	public void setNonApproval1(String nonApproval1) {
		this.nonApproval1 = nonApproval1;
	}

	public String getNonApproval2() {
		return this.nonApproval2;
	}

	public void setNonApproval2(String nonApproval2) {
		this.nonApproval2 = nonApproval2;
	}

	public Organ getParentOrgan() {
		return this.parentOrgan;
	}

	public void setParentOrgan(Organ parentOrgan) {
		this.parentOrgan = parentOrgan;
	}

	public Set<UserGroup> getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(Set<UserGroup> userGroups) {
		this.userGroups = userGroups;
	}

}
